# Generated by Django 5.2.12 on 2026-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Время (срок действия)')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'db_table': 'qr',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, verbose_name='Состояние')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'db_table': 'status',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=128, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Кол-во')),
                ('pickup_point', models.CharField(max_length=500, verbose_name='Точка вывоза')),
            ],
            options={
                'db_table': 'othody',
            },
        ),
    ]
