# Generated by Django 5.2.12 on 2026-03-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='delivery_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='users.recycler', verbose_name='Образователь'),
        ),
        migrations.AddField(
            model_name='waste',
            name='medical_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='users.medicalorganization', verbose_name='Образователь'),
        ),
        migrations.AddField(
            model_name='status',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='batches.waste', verbose_name='id_отходов'),
        ),
        migrations.AddField(
            model_name='qr',
            name='waste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='batches.waste', verbose_name='id_отходов'),
        ),
    ]
