# Generated by Django 6.0.3 on 2026-03-21 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_initial'),
        ('users', '0002_user_driver_profile_user_is_staff_user_medical_org_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='time',
        ),
        migrations.AddField(
            model_name='qr',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qrs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='qr',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='status',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён'),
        ),
        migrations.AddField(
            model_name='waste',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wastes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='waste',
            name='current_status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('IN_TRANSIT', 'В пути'), ('DELIVERED', 'Доставлена'), ('ACCEPTED', 'Принята переработчиком'), ('CANCELLED', 'Отменена')], default='CREATED', max_length=16, verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='waste',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr', to='batches.waste', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='status',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('IN_TRANSIT', 'В пути'), ('DELIVERED', 'Доставлена'), ('ACCEPTED', 'Принята переработчиком'), ('CANCELLED', 'Отменена')], max_length=16, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='status',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='batches.waste', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='delivery_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='users.recycler', verbose_name='Переработчик'),
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(max_length=64, verbose_name='Сканированный код')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('fail_reason', models.CharField(blank=True, max_length=128, verbose_name='Причина отказа')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='batches.qr', verbose_name='QR')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='Кто сканировал')),
            ],
            options={
                'db_table': 'qr_scan_log',
                'ordering': ('-scanned_at',),
            },
        ),
    ]
