# Generated by Django 5.2.12 on 2026-03-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=64, verbose_name='Номер ТС')),
            ],
            options={
                'db_table': 'vod',
            },
        ),
        migrations.CreateModel(
            name='MedicalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=128, verbose_name='Лицензия')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
            ],
            options={
                'db_table': 'obr',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('RECYCLER', 'Образователь'), ('DRIVER', 'Водитель'), ('MEDICAL', 'Переработчик'), ('INSPECTOR', 'Инспектор'), ('ADMIN', 'Администратор')], max_length=16, verbose_name='Роль')),
                ('login', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organization', verbose_name='Организация')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=128, verbose_name='Номер лицензии')),
                ('facility_address', models.CharField(max_length=500, verbose_name='Адрес площадки')),
                ('drivers', models.ManyToManyField(blank=True, related_name='recyclers', to='users.driverprofile', verbose_name='Список водителей')),
            ],
            options={
                'db_table': 'pererabotchik',
            },
        ),
    ]
