# Generated by Django 5.2.12 on 2026-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=64, verbose_name='Тип объекта')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID объекта')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='До')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='После')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ('-created_at',),
            },
        ),
    ]
