# Generated by Django 5.2.12 on 2026-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'db_table': 'org',
                'unique_together': {('inn', 'kpp')},
            },
        ),
    ]
